[package]
name = "eggie-protocol"
version = "0.0.1-alpha.3"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
eggie-domain.workspace = true
base64.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true

[dev-dependencies]
rmp-serde.workspace = true
uuid.workspace = true
